plugins:
  - jekyll-katex
  - jekyll-minifier

highlihger: rouge

permalink: /:categories/:year/:month/:day/:title/
collections:
  emacspeak_tutorials:
    output: true
    permalink: /emacspeak-tutorials/:name/
