plugins:
  - jekyll-katex
  - jekyll-minifier
  - kramdown-math-katex

highlihger: rouge

permalink: /:categories/:year/:month/:day/:title/

collections:
  emacspeak_tutorials:
    output: true
    permalink: /emacspeak-tutorials/:name/
  book_notes:
    output: true
    permalink: /book-notes/:name/

markdown: kramdown
kramdown:
  math_engine: katex

scholar:
  style: "ieee"
